import Link from "next/link";
import "./globals.css";
import { Control } from "./Control";

export const metadata = {
  title: "넥스트js 페이지",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const resp = await fetch(`${process.env.NEXT_PUBLIC_API_SERVER}topics`);
  const topics = await resp.json();
  //console.log("Topics", topics);
  return (
    <html lang="en">
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map((topic) => {
            return (
              <li key={topic.id}>
                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              </li>
            );
          })}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  );
}
